from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
import os
import shutil
import uuid
import logging
from main import run_pipeline

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("server.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

app = FastAPI()

# Temporary directory for processing
UPLOAD_DIR = "uploads"
STATIC_DIR = "static"
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(STATIC_DIR, exist_ok=True)

# Copy style.css to static if it exists
if os.path.exists("style.css"):
    shutil.copy("style.css", os.path.join(STATIC_DIR, "style.css"))

app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

@app.get("/", response_class=HTMLResponse)
async def get_index():
    if os.path.exists("index.html"):
        with open("index.html", "r", encoding="utf-8") as f:
            return f.read()
    return "<h1>Frontend Error: index.html not found</h1>"

@app.post("/upload")
async def upload_pdf(file: UploadFile = File(...)):
    if not file.filename.endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are allowed")

    task_id = str(uuid.uuid4())
    input_base = os.path.join(UPLOAD_DIR, task_id)
    os.makedirs(input_base, exist_ok=True)
    
    input_path = os.path.join(input_base, "input.pdf")
    output_path = os.path.join(input_base, "output.xlsx")

    # Save uploaded file
    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    try:
        logger.info(f"Processing task {task_id}")
        run_pipeline(input_path, output_path)
        
        if not os.path.exists(output_path):
             raise Exception("Excel file was not generated by the pipeline.")
             
        logger.info(f"Task {task_id} completed successfully. Result at {output_path}")
        return {"success": True, "download_url": f"/download/{task_id}"}
    except Exception as e:
        logger.error(f"Error processing PDF: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Pipeline Error: {str(e)}")

@app.get("/download/{task_id}")
async def download_file(task_id: str):
    output_path = os.path.join(UPLOAD_DIR, task_id, "output.xlsx")
    if os.path.exists(output_path):
        return FileResponse(
            output_path, 
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", 
            filename="seat_ibiza_processed.xlsx"
        )
    raise HTTPException(status_code=404, detail="File not found or expired")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
